# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 23:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=128, verbose_name='题目')),
                ('answer', models.CharField(blank=True, max_length=128, verbose_name='参考答案')),
                ('level', models.CharField(choices=[('simple', '简单'), ('medium', '中等'), ('hard', '困难')], default='simple', max_length=12, verbose_name='难易度')),
                ('value', models.DecimalField(blank=True, decimal_places=1, max_digits=2, verbose_name='分值')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='增加时间')),
            ],
            options={
                'verbose_name': '分析题',
                'verbose_name_plural': '分析题',
                'db_table': 'AnalysisProfile',
            },
        ),
        migrations.CreateModel(
            name='CompletionProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=128, verbose_name='题目')),
                ('answerA', models.CharField(blank=True, max_length=32, verbose_name='第一空答案')),
                ('answerB', models.CharField(blank=True, max_length=32, verbose_name='第二空答案')),
                ('level', models.CharField(choices=[('simple', '简单'), ('medium', '中等'), ('hard', '困难')], default='simple', max_length=12, verbose_name='难易度')),
                ('value', models.DecimalField(blank=True, decimal_places=1, max_digits=2, verbose_name='分值')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='增加时间')),
            ],
            options={
                'verbose_name': '填空题',
                'verbose_name_plural': '填空题',
                'db_table': 'CompletionProfile',
            },
        ),
        migrations.CreateModel(
            name='CourseProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='课程名')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='增加时间')),
            ],
            options={
                'verbose_name': '课程名',
                'verbose_name_plural': '课程名',
                'db_table': 'CourseProfile',
            },
        ),
        migrations.CreateModel(
            name='ExamProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, verbose_name='结束时间')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='增加时间')),
            ],
            options={
                'verbose_name': '考试列表',
                'verbose_name_plural': '考试列表',
                'db_table': 'ExamProfile',
            },
        ),
        migrations.CreateModel(
            name='JudgmentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=128, verbose_name='题目')),
                ('answer', models.CharField(blank=True, choices=[('T', '正确'), ('F', '错误')], max_length=12, verbose_name='难易度')),
                ('level', models.CharField(choices=[('simple', '简单'), ('medium', '中等'), ('hard', '困难')], default='simple', max_length=12, verbose_name='难易度')),
                ('value', models.DecimalField(blank=True, decimal_places=1, max_digits=2, verbose_name='分值')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='增加时间')),
            ],
            options={
                'verbose_name': '判断题',
                'verbose_name_plural': '判断题',
                'db_table': 'JudgmentProfile',
            },
        ),
        migrations.CreateModel(
            name='MchoiceProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=128, verbose_name='题目')),
                ('optionA', models.CharField(blank=True, max_length=64, verbose_name='选项A')),
                ('optionB', models.CharField(blank=True, max_length=64, verbose_name='选项B')),
                ('optionC', models.CharField(blank=True, max_length=64, verbose_name='选项C')),
                ('optionD', models.CharField(blank=True, max_length=64, verbose_name='选项D')),
                ('optionE', models.CharField(blank=True, max_length=64, verbose_name='选项E')),
                ('answer', models.CharField(blank=True, max_length=12, verbose_name='正确答案')),
                ('level', models.CharField(choices=[('simple', '简单'), ('medium', '中等'), ('hard', '困难')], default='simple', max_length=12, verbose_name='难易度')),
                ('value', models.DecimalField(blank=True, decimal_places=1, max_digits=2, verbose_name='分值')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='增加时间')),
            ],
            options={
                'verbose_name': '选择题',
                'verbose_name_plural': '选择题',
                'db_table': 'MchoiceProfile',
            },
        ),
        migrations.CreateModel(
            name='MoremchoiceProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=128, verbose_name='题目')),
                ('optionA', models.CharField(blank=True, max_length=64, verbose_name='选项A')),
                ('optionB', models.CharField(blank=True, max_length=64, verbose_name='选项B')),
                ('optionC', models.CharField(blank=True, max_length=64, verbose_name='选项C')),
                ('optionD', models.CharField(blank=True, max_length=64, verbose_name='选项D')),
                ('optionE', models.CharField(blank=True, max_length=64, verbose_name='选项E')),
                ('answers', models.CharField(blank=True, max_length=12, verbose_name='正确答案')),
                ('level', models.CharField(choices=[('simple', '简单'), ('medium', '中等'), ('hard', '困难')], default='simple', max_length=12, verbose_name='难易度')),
                ('value', models.DecimalField(blank=True, decimal_places=1, max_digits=2, verbose_name='分值')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='增加时间')),
            ],
            options={
                'verbose_name': '选择题',
                'verbose_name_plural': '选择题',
                'db_table': 'MoremchoiceProfile',
            },
        ),
        migrations.CreateModel(
            name='TestProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mchoice_id', models.CharField(blank=True, max_length=128, verbose_name='单选题ID')),
                ('moremchoice_id', models.CharField(blank=True, max_length=128, verbose_name='多选题ID')),
                ('judgment_id', models.CharField(blank=True, max_length=128, verbose_name='判断题ID')),
                ('completion_id', models.CharField(blank=True, max_length=128, verbose_name='填空题ID')),
                ('analysis_id', models.CharField(blank=True, max_length=128, verbose_name='分析题ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='增加时间')),
            ],
            options={
                'verbose_name': '试卷信息',
                'verbose_name_plural': '试卷信息',
                'db_table': 'TestProfile',
            },
        ),
    ]
