# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-03 20:37
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamGradeCountProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.CharField(blank=True, max_length=64, verbose_name='考试ID')),
                ('gradecount', models.IntegerField(blank=True, verbose_name='考试成绩')),
                ('student', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '考试成绩',
                'verbose_name_plural': '考试成绩',
                'db_table': 'ExamGradeCountProfile',
            },
        ),
        migrations.CreateModel(
            name='ExamProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='增加时间')),
                ('exam_id', models.CharField(blank=True, max_length=64, verbose_name='考试ID')),
                ('course', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.CourseProfile', verbose_name='课程名')),
                ('createuser', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '考试列表',
                'verbose_name_plural': '考试列表',
                'db_table': 'ExamProfile',
            },
        ),
    ]
