# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 01:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='deptname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.DeptProfile', verbose_name='部门名称'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='female', max_length=6, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='电话号码'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('s', '学生'), ('t', '教师'), ('a', '教务管理员')], default='s', max_length=6, verbose_name='角色'),
        ),
    ]
