# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171029_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', '学生'), ('teacher', '教师'), ('admin', '教务管理员')], default='s', max_length=6, verbose_name='角色'),
        ),
    ]
