# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 23:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='增加时间')),
            ],
            options={
                'verbose_name': '学生考试关联表',
                'verbose_name_plural': '学生考试关联表',
                'db_table': 'StudentExam',
            },
        ),
    ]
