# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentexam_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexam',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='考试是否完成'),
        ),
    ]
